name = "Coder"
license = "MIT"
licenselink = "https://github.com/"
description = "A simple and clean blog theme for"
homepage = "https://github.com/"
tags = [
  "blog",
  "minimal",
  "minimalist",
  "responsive",
  "simple",
  "clean",
  "personal"
]
features = [
  "analytics",
  "favicon",
  "multilingual",
  "pagination",
  "single-column",
  "syntax-highlighting"
]
min_version = "0.77.0"

[author]
name = ""
homepage = "https://.com"
